name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push the Producer's image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./producer/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: wcygan/kafka-on-kubernetes-producer:latest
          cache-from: type=registry,ref=wcygan/kafka-on-kubernetes-producer:latest
          cache-to: type=inline
      -
        name: Build and push the Consumer's image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./consumer/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: wcygan/kafka-on-kubernetes-consumer:latest
          cache-from: type=registry,ref=wcygan/kafka-on-kubernetes-consumer:latest
          cache-to: type=inline